name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  send_notification:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure() 
    steps:
      - name: Send Telegram notification on success
        if: success()
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "Успех! Сборка прошла успешно."}' https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage
      - name: Send Telegram notification on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "Ошибка! Сборка не удалась."}' https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage
